/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import static database.DB_Connection.*;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohan babar
 */
public class Bill_list extends javax.swing.JFrame {

    /**
     * Creates new form Bill_list
     */
    public Bill_list() {
        initComponents();
        clearTable();
        displayBillDetails();
    }

     //Display Bill list in the bill_tbl table
  void displayBillDetails()
    {
         Connection con =getConnection();//accessing database connection from DB_Connection class
        try {
              stmt=con.createStatement();//create Statement
             ResultSet rs=stmt.executeQuery("select * from Bill_details");
           while(rs.next())
            {
                //data will be added until finish
               
                String billno=String.valueOf(rs.getInt("Bill_No"));
                String billdate=String.valueOf(rs.getDate("Bill_Date"));
                String billtype=rs.getString("Bill_Type");
                String opdtype=String.valueOf(rs.getString("OPD_Type"));
                String opdno=String.valueOf(rs.getInt("OPD_No"));
                String patientname=rs.getString("Patient_Name");
                String pregno=String.valueOf(rs.getInt("PRegNo"));  
                String service=rs.getString("Services");
                String samount=rs.getString("Service_Amount");
                String discount=rs.getString("Discount");
                 String total=rs.getString("Total_Amount");
                  String paymode=rs.getString("PayMode");
                
                //String array for store dara into bill_tbl
                String tbData[]={ billno,billdate,billtype,opdtype,opdno,patientname,pregno,service,samount,discount,total,paymode};
                DefaultTableModel model=(DefaultTableModel)bill_tbl.getModel();  
                //add String array data into bill_tbl
                model.addRow(tbData);
            }
           con.close();//connection close
        } catch (Exception e) {
           e.printStackTrace();
       }
    }
    
   //method to clear table
   void clearTable()
    {
        //to clear all data from bill_tbl
      DefaultTableModel tmodel=(DefaultTableModel) bill_tbl.getModel();
      tmodel.setRowCount(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill_tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        View = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 249, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bill_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No.", "Bill Date", "Bill Type", "OPD Type", "OPD No.", "Patient Name", "Patient Reg No.", "Service Used", "Service Amount", "Discount", "Grand Total", "Pay Mode"
            }
        ));
        bill_tbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        bill_tbl.setFocusable(false);
        bill_tbl.setGridColor(new java.awt.Color(102, 102, 102));
        bill_tbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        bill_tbl.setRowHeight(28);
        bill_tbl.setShowVerticalLines(false);
        bill_tbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(bill_tbl);
        if (bill_tbl.getColumnModel().getColumnCount() > 0) {
            bill_tbl.getColumnModel().getColumn(0).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(0).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(1).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(1).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(2).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(2).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(3).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(3).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(4).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(4).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(5).setMinWidth(150);
            bill_tbl.getColumnModel().getColumn(5).setMaxWidth(200);
            bill_tbl.getColumnModel().getColumn(6).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(6).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(7).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(7).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(8).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(8).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(9).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(9).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(10).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(10).setMaxWidth(150);
            bill_tbl.getColumnModel().getColumn(11).setMinWidth(100);
            bill_tbl.getColumnModel().getColumn(11).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 910, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Bill List");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 200, 40));

        back.setFont(new java.awt.Font("Yu Gothic", 1, 23)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 51));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        View.setBackground(new java.awt.Color(0, 0, 255));
        View.setForeground(new java.awt.Color(255, 255, 255));
        View.setText("View ");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel1.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 550, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 1000, 650));

        setBounds(400, 90, 998, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
      dispose();//causes the JFrame window to be distroyed
    }//GEN-LAST:event_backMouseClicked

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
         if(bill_tbl.getSelectedRowCount()==1)
        {
           ViewBill view=new ViewBill();
           view.setVisible(true);
           dispose();
        }
        else
        {
            if(bill_tbl.getRowCount()==0)
            {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "No any Bill details in bill  list");//show message
            }
            else
            {
                //if row is not selected
                JOptionPane.showMessageDialog(this, "select the  bill details ");//show message
            }
        }
    }//GEN-LAST:event_ViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JLabel back;
    public static javax.swing.JTable bill_tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
