/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import static database.DB_Connection.*;
import java.sql.Connection;
import java.sql.ResultSet;
/**
 *
 * @author Mohan babar
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setDataToCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //here we set the total count of patient ,appointments and bill to dashboard
    public void setDataToCards(){
        try {
               Connection con =getConnection();//accessing database connection from DB_Connection class
               stmt=con.createStatement();//create statment 
               //select data from Patient table
              ResultSet rs=stmt.executeQuery("Select * from Patient");
              rs.last();// rs gose to last rwo
              TotalPatient.setText(Integer.toString(rs.getRow()));
              
              //Select data from appointment table
              rs=stmt.executeQuery("Select * from Appointment");
              rs.last();
              Total_appt.setText(Integer.toString(rs.getRow()));
              //select data from Bill_details table
              rs=stmt.executeQuery("Select * from Bill_details");
              rs.last();
              Total_bills.setText(Integer.toString(rs.getRow()));
                   
        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        Total_bills = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        TotalPatient = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        Total_appt = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 102, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 18, 0, new java.awt.Color(255, 51, 102)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Total_bills.setFont(new java.awt.Font("Rockwell", 0, 50)); // NOI18N
        Total_bills.setForeground(new java.awt.Color(255, 255, 255));
        Total_bills.setText("10");
        jPanel16.add(Total_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, -1));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Total Bill Generated");
        jPanel16.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, -1));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 260, 140));

        jPanel17.setBackground(new java.awt.Color(0, 102, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 18, 0, new java.awt.Color(0, 51, 204)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalPatient.setFont(new java.awt.Font("Rockwell", 0, 50)); // NOI18N
        TotalPatient.setForeground(new java.awt.Color(255, 255, 255));
        TotalPatient.setText("10");
        jPanel17.add(TotalPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total Patient Registered");
        jPanel17.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 260, 140));

        jPanel18.setBackground(new java.awt.Color(0, 102, 102));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 18, 0, new java.awt.Color(0, 153, 153)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Total_appt.setFont(new java.awt.Font("Rockwell", 0, 50)); // NOI18N
        Total_appt.setForeground(new java.awt.Color(255, 255, 255));
        Total_appt.setText("10");
        jPanel18.add(Total_appt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Appointments");
        jPanel18.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, -1));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 260, 140));

        Back.setFont(new java.awt.Font("Yu Gothic", 1, 23)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 0, 51));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        setBounds(400, 100, 990, 593);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
       
        dispose();//causes the JFrame window to be distroyed
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel TotalPatient;
    private javax.swing.JLabel Total_appt;
    private javax.swing.JLabel Total_bills;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    // End of variables declaration//GEN-END:variables
}
