/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import static database.DB_Connection.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohan babar
 */
public class ViewBill extends javax.swing.JFrame {

    /**
     * Creates new form ViewBill
     */
    public ViewBill() {
        initComponents();
        billDisplay();//call method 
        fetchDataBill_details();
        fetchDataPatient();
    }

    //to display bill receipt 
    void billDisplay()
    {
        DefaultTableModel tbmodel=(DefaultTableModel)Bill_list.bill_tbl.getModel();
        //set data to textfield  when row is selected 
        int index=Bill_list.bill_tbl.getSelectedRow();
         billno.setText(tbmodel.getValueAt(index, 0).toString());
        opdtype.setText(tbmodel.getValueAt(index, 3).toString());
        opdno.setText(tbmodel.getValueAt(index, 4).toString());
        name.setText(tbmodel.getValueAt(index, 5).toString());
        regno.setText(tbmodel.getValueAt(index, 6).toString());
         sbill.setText(tbmodel.getValueAt(index, 7).toString());
           amtbill.setText("Rs."+tbmodel.getValueAt(index, 8).toString());
             disBill.setText(tbmodel.getValueAt(index, 9).toString());
              grandBill.setText("Rs."+tbmodel.getValueAt(index, 10).toString());
                pay.setText(tbmodel.getValueAt(index, 11).toString());
        //set  date to JDatechooser when row is selected 
         try {
            java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse((String)tbmodel.getValueAt(index, 1).toString());
           String d=DateFormat.getDateInstance().format(date);
            billdate.setText(d);
        } catch (Exception e) {
           e.printStackTrace();
        }
    }
    //fetch the data from bill_details table
    void fetchDataBill_details()
    {
        try {
              Connection con =getConnection();
               stmt=con.createStatement();//create Statement
            int data=Integer.parseInt(regno.getText());
             ResultSet rs=stmt.executeQuery("select Quantity,DisType from Bill_details where PRegNo ="+data+";");
             while(rs.next()){
                  int qua=rs.getInt("Quantity");
              String dtype=rs.getString("DisType");
               quan.setText(Integer.toString(qua));
              typebill.setText(dtype);
             }
            
             
        } catch (Exception e) {
        }
       
    }
    
    //fetch data from Patient table
    void fetchDataPatient()
    {
        try {
              Connection con =getConnection();
               stmt=con.createStatement();//create Statement
            int value=Integer.parseInt(regno.getText());
             ResultSet rs=stmt.executeQuery("select Address,Mobile from Patient where Register_No ="+value+";");
             while(rs.next()){
                  String pho=rs.getString("Mobile");
              String padd=rs.getString("Address");
               mob.setText(pho);
              address.setText(padd);
             }
            
             
        } catch (Exception e) {
        }
       
    }
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        billno = new javax.swing.JLabel();
        billdate = new javax.swing.JLabel();
        opdtype = new javax.swing.JLabel();
        service = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        mob = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        opdno = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        regno = new javax.swing.JLabel();
        sbill = new javax.swing.JLabel();
        quan = new javax.swing.JLabel();
        amtbill = new javax.swing.JLabel();
        service4 = new javax.swing.JLabel();
        service5 = new javax.swing.JLabel();
        typebill = new javax.swing.JLabel();
        disBill = new javax.swing.JLabel();
        service8 = new javax.swing.JLabel();
        grandBill = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(167, 114, 114));
        jLabel1.setText("Healthcare Clinic ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("23,Acacia Gardends -1,Magarpatta,Hadapsar,pune,Maharadhtra 411013");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 450, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Bill Receipt");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, 40));

        Back.setFont(new java.awt.Font("Yu Gothic", 1, 23)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 0, 51));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 150));

        jPanel2.setBackground(new java.awt.Color(167, 114, 114));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bill to");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 790, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Reg No.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        billno.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 70, 30));

        billdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(billdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 150, 30));

        opdtype.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(opdtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 150, 30));

        service.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        service.setForeground(new java.awt.Color(0, 0, 255));
        service.setText("Grand Total");
        jPanel3.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 120, 30));

        name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 250, 30));

        address.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 250, 30));

        mob.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Name:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Address:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Mobile No.");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 30));

        opdno.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(opdno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, 30));

        pay.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 180, 30));

        jPanel4.setBackground(new java.awt.Color(167, 114, 114));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Amount");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 100, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Service used");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quantity");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Price");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 140, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 790, 30));

        jPanel5.setBackground(new java.awt.Color(167, 114, 114));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 780, 30));

        regno.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 30));

        sbill.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(sbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        quan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 100, 30));

        amtbill.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(amtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 140, 30));

        service4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        service4.setForeground(new java.awt.Color(0, 0, 255));
        service4.setText("Discount Type");
        jPanel3.add(service4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 120, 30));

        service5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        service5.setForeground(new java.awt.Color(0, 0, 255));
        service5.setText("Discount");
        jPanel3.add(service5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 120, 30));

        typebill.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(typebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 140, 30));

        disBill.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel3.add(disBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 140, 30));

        service8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        service8.setForeground(new java.awt.Color(0, 0, 255));
        service8.setText("Total Amount");
        jPanel3.add(service8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, 30));

        grandBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grandBill.setForeground(new java.awt.Color(0, 204, 51));
        jPanel3.add(grandBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Bill No:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Date:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 50, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("OPD Type:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 80, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("OPD No.");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Payment Mode:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 30));

        Print.setBackground(new java.awt.Color(0, 0, 204));
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel3.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 790, 470));

        setBounds(400, 100, 780, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
    
        dispose();//causes the JFrame window to be distroyed
    }//GEN-LAST:event_BackMouseClicked

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Please Connect the Printer");//show message 
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JButton Print;
    private javax.swing.JLabel address;
    private javax.swing.JLabel amtbill;
    private javax.swing.JLabel billdate;
    private javax.swing.JLabel billno;
    private javax.swing.JLabel disBill;
    private javax.swing.JLabel grandBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mob;
    private javax.swing.JLabel name;
    private javax.swing.JLabel opdno;
    private javax.swing.JLabel opdtype;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel quan;
    private javax.swing.JLabel regno;
    private javax.swing.JLabel sbill;
    private javax.swing.JLabel service;
    private javax.swing.JLabel service4;
    private javax.swing.JLabel service5;
    private javax.swing.JLabel service8;
    private javax.swing.JLabel typebill;
    // End of variables declaration//GEN-END:variables
}
